<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="LAPTOP-KAJ8NU67" ignored="2" name="Test" tests="5" failures="2" timestamp="20 Jun 2019 17:51:51 GMT" time="6.547" errors="0">
  <testcase name="logout" time="0.007" classname="testcases.Dataprovider"/>
  <testcase name="logout" time="0.002" classname="testcases.Dataprovider"/>
  <testcase name="logout" time="0.001" classname="testcases.Dataprovider"/>
  <testcase name="testCase" time="0.001" classname="testcases.FullTask">
    <failure type="org.testng.internal.reflect.MethodMatcherException" message="
Data provider mismatch
Method: testCase([Parameter{index=0, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=1, type=java.lang.String, declaredAnnotations=[]}])
Arguments: [(java.lang.String) tutorial]">
      <![CDATA[org.testng.internal.reflect.MethodMatcherException: 
Data provider mismatch
Method: testCase([Parameter{index=0, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=1, type=java.lang.String, declaredAnnotations=[]}])
Arguments: [(java.lang.String) tutorial]
... Removed 20 stack frames]]>
    </failure>
  </testcase> <!-- testCase -->
  <testcase name="softassertion" time="0.011" classname="testcase2.Assertion">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [Excepted] but found [actalTitle]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [Excepted] but found [actalTitle]
at testcase2.Assertion.softassertion(Assertion.java:35)
... Removed 26 stack frames]]>
    </failure>
  </testcase> <!-- softassertion -->
  <testcase name="dataprovider" time="0.0" classname="testcases.Dataprovider">
    <ignored/>
  </testcase> <!-- dataprovider -->
  <testcase name="assertion" time="0.0" classname="testcase2.Assertion">
    <ignored/>
  </testcase> <!-- assertion -->
</testsuite> <!-- Test -->
